### ISSUE TITLE
 RangeError (RangeError: _readBytes has fewer bytes than expected.)

### ISSUE THREAD

**Issue by nns52k** [LacticWhale/socks_dart#8] opened 2024-04-30 10:48 UTC
For details, please check https://github.com/Foundation-Devices/tor/issues/41#issue-2271120120

**Comment by LacticWhale** [comment] 2024-04-30 12:54
Haven't I already said it's caused by connection closing on server side.
I will add proper way to handle it later. Right now I am waiting for feature to be added in Dart SDK.

**Comment by nns52k** [comment] 2024-04-30 13:28
> Haven't I already said it's caused by connection closing on server side. I will add proper way to handle it later. Right now I am waiting for feature to be added in Dart SDK.

But connecting to an external Tor process works just fine. Are you sure it's a bug in package `socks5_proxy` instead of package `tor`?

**Comment by LacticWhale** [comment] 2024-05-04 12:05
It's not a bug, it's feature that have not yet been documented.

**Comment by nns52k** [comment] 2024-05-04 14:44
> It's not a bug, it's feature that have not yet been documented.

Just wondering, any chance we could get an option to switch off this feature?

Your Dart package stands out as the most promising among others I've come across. Can't wait to surf onion servers with this awesome package! Huge thanks for all your hard work; it's seriously appreciated!

**Comment by LacticWhale** [comment] 2024-05-04 21:04
@nns52k 
I changed Erorr to Exception (was my fault I wrote that code before I knew most of guidelines) in ByteReader so now you can catch `ByteReaderException` or `SocksClientException` if server closes connection without stating a reason (which is valid according to socks documentation). 
For all new changes see [CHANGELOG.md](../blob/master/CHANGELOG.md)

**Closed as completed by LacticWhale** 2024-05-04 21:04 UTC
